### PR TITLE
Add APOLLO_KEY for Apollo Metrics reporting

### PR DESCRIPTION
**Pull request by ryanahamilton**
Part of astronomer/issues#1144.

### CODE REVIEW

**Comment by schnie** [comment]
@ryanahamilton we may want to keep these as a secret and out of the source code here. @sjmiller609 what do you think? Should we treat this like the stripe key?

**Comment by sjmiller609** [comment]
yeah, even for keys or strings that are not secret I would like to manage in secrets because it's just ugly. the secrets set up is a bit wild, but I can help out with that. we are still using my initial design of bucket with secrets in it, then have terraform make an authenticated link then download that link using the http module. that stuff is in the secrets.tf and it should be easy enough to add. I will handle adding these to the buckets.

@ryanahamilton if this is actually a secret, please rotate the credentials.

**Comment by ryanahamilton** [comment]
Makes sense. I’ll rotate and send to you.

**Comment by sjmiller609** [comment]
I'm going to ship this after 0.13

**Comment by sjmiller609** [comment]
sorry for the delay, I'm on it now

**Pull request merged**
