### PR TITLE
Use internal helm

### PR DESCRIPTION
**Pull request by danielhoherd**
# Primary changes:

* Use internal-helm.astronomer.io as astronomer-internal helm repo for installation source

# Secondary changes

* Rework common args into array
* Simplify some variable munging
* Delete unused variables
* Lots of shellcheck recommended cleanup related to quotes and exporting vars
* Use ipify.org instead of icanhazip.com

### CODE REVIEW

**Comment by jpweber** [comment]
@sjmiller609 Do you want to take a peek before we merge? I know you've done a lot of work on this before.

**Comment by sjmiller609** [comment]
There is a one-time concern regarding the existing artifacts. I expect on merge this will fail on helm upgrade on account of internal helm repo not containing the version specified in app/environment files

**Comment by sjmiller609** [comment]
@danielhoherd can you copy just this version to the internal helm repo https://github.com/astronomer/google-environments/blob/master/staging/cloud/app/environment, please? I prefer to not copy everything by the way.

**Comment by danielhoherd** [comment]
@sjmiller609 done.

```sh
$ helm search repo astronomer-internal
NAME                          	CHART VERSION	APP VERSION	DESCRIPTION
astronomer-internal/astronomer	0.16.2       	0.16.2     	Helm chart to deploy the Astronomer Platform
```

**Pull request merged**
