### PR TITLE
Add AC 1.10.5-9, 1.10.7-13 and 1.10.10-3 Docker Images

### PR DESCRIPTION
**Pull request by kaxil**
- astronomer/ap-airflow#107
- astronomer/ap-airflow#109
- astronomer/ap-airflow#106

### CODE REVIEW

**Comment by kaxil** [comment]
Ping @sjmiller609 @schnie

**Comment by sjmiller609** [comment]
@kaxil please make this not a draft when you consider it prod ready

**Comment by kaxil** [comment]
> @kaxil please make this not a draft when you consider it prod ready

Done

**Comment by sjmiller609** [comment]
ty!

**Pull request merged**
